As a first App, lets create a normal Hello World: ::

    #include "AquaOS.h"

    namespace hello_world {
      void startScreen() {
        drawCenteredString(PSTR("Hello World!"));
        toolbarAddHome();
      }
    }

All the code must be inside the given namespace. This ensures that all different Apps won't 
collide during compilation.

The code to draw the main screen of the app goes inside the function *startScreen*.

It is *very* *very* important that all string literals are inside the PSTR macro. If not
sketches will crash when executed in a microcontroller.

The last instruction adds a button on the toolbar, to go back to the Desktop (Home).

.. image:: images/hello_world.png

Lorem ipsum [#f1]_ dolor sit amet ... [#f2]_

.. rubric:: Footnotes

.. [#f1] Text of the first footnote.
.. [#f2] Text of the second footnote.